apiVersion: v1
kind: Service
metadata:
  name: triton
  namespace: gpu-inference
  labels:
    app: triton
spec:
  selector:
    app: triton
  ports:
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: http
      port: 8002
      targetPort: 8002
    - name: metrics
      port: 8003
      targetPort: 8003
  type: ClusterIP
